---
title: "Hello, Tutorial!"
author: "Simon Knight, modified from J.J. Allaire"
date: "`r Sys.Date()`"
output: learnr::tutorial
runtime: shiny_prerendered
# Do not index/display tutorial by setting `private: true`
# private: true
description: >
  This is a demo tutorial.
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(learnrhash)
library(pacman)
p_load(kandinsky,morsecode, phonenumber, secrettext,tibble,ggplot2)

gradethis::gradethis_setup()
tutorial_options(exercise.checker = gradethis::grade_learnr)
##############
#converts letters to numbers
letter2num <- function(x) {utf8ToInt(x) - utf8ToInt("a") + 1L}
LETTER2num <- function(x) {utf8ToInt(x) - utf8ToInt("A") + 1L}
#unname(sapply("ABC", LETTER2num))
let2n <- function(x) { 
  
  x <- unlist(strsplit(x, split = ""))
  
  sapply(x, function(y) { 
    unlist(strsplit(y, split = ""))
  
  if(grepl("[[:upper:]]", y)) {
    LETTER2num(y)
} else {
    letter2num(y)
}
  }   ) }


tut_reptitle <- "Hello world"
```

The following code computes the answer to 1+1. Change it so it computes 2 + 2:

```{r addition, exercise=TRUE}
1 + 1
```

```{r addition-solution}
2 + 2
```

```{r addition-code-check}
grade_code()
```


## Submit answers

I care more about you attempting these than 100% correct answers. 

To submit, generate your answer below, and paste it into the google form provided. 

```{r passr, message=FALSE, warning=FALSE, include=FALSE}
#this file gets included/sourced/child rmd into each learnr Rmd. It means I can update how things get submitted on all tutorials without needing to manually edit them all.

#see passr project file for ideas for other ways to do this (email, gdrive distrib, etc.)

library(learnrhash)
```


```{r encode-me, context="server"}

learnrhash::encoder_logic()

#learnSTATS::encoder_logic()
```

### Use the copy and paste function to submit this to the form

```{r encode-ui, echo=FALSE}

learnrhash::encoder_ui(ui_before = NULL, ui_after = NULL)

```

### If you want to check what the hash shows, use the decoder

```{r context="server"}
learnrhash::decoder_logic()
```


```{r decode-ui, echo=FALSE}
learnrhash::decoder_ui()
```

